// <auto-generated />
using System;
using Fora.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fora.Infra.Data.Migrations
{
    [DbContext(typeof(ForaContext))]
    [Migration("20251120143255_new database")]
    partial class newdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fora.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Cik")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Cik");

                    b.HasIndex("Cik")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("Fora.Domain.Entities.CompanyNetIncomeLoss", b =>
                {
                    b.Property<Guid>("CompanyNetIncomeLossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cik")
                        .HasColumnType("int");

                    b.Property<string>("LossFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LossFrame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LossValue")
                        .HasColumnType("bigint");

                    b.HasKey("CompanyNetIncomeLossId");

                    b.HasIndex("Cik");

                    b.ToTable("CompanyNetIncomeLoss", (string)null);
                });

            modelBuilder.Entity("Fora.Domain.Entities.WebUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserName");

                    b.ToTable("WebUser", (string)null);

                    b.HasData(
                        new
                        {
                            UserName = "guest",
                            Password = "h1eTenbV4CdRr5fYIYmiq/1mg+6i3WL7ELVS0WsLmB8=",
                            Role = "Guest"
                        });
                });

            modelBuilder.Entity("Fora.Domain.Entities.CompanyNetIncomeLoss", b =>
                {
                    b.HasOne("Fora.Domain.Entities.Company", "Company")
                        .WithMany("CompanyNetIncomeLoss")
                        .HasForeignKey("Cik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Fora.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyNetIncomeLoss");
                });
#pragma warning restore 612, 618
        }
    }
}
